version: "3.8"

services:
  learnc:
    image: learnc:dev
    container_name: learnc
    hostname: learnc
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - $PWD:/app
    tty: true
